theme: jekyll-theme-dinky
title: [2020 Workshop on Transparency, Reproducibility, Extensibility and Sustainability (TRES-2020)]
description: [TRES-2020 brings together diverse elements of the scientific community to discuss and determine the roles, responsibilities, authority and accountability for transparency, reproducibility, extensibility and sustainability of computational science results.]
